### ISSUE TITLE
Allow unschematized data to pass through

### ISSUE THREAD

**Issue by alex-dixon** [Effect-TS/schema#226]
## 📖 Documentation
Hello!

In io-ts, t.type allows excessive properties. It appears S.struct strips these by default with an option to error on them instead.

What is the recommended way to achieve the t.type behavior? I.e. allow excessive properties to pass through while still ensuring the specified type is satisfied.

**Comment by gcanti** [comment]
At the schema level you could add an index signature `{ readonly [x: string]: unknown; }` to the schema type (as it also does zod):

```ts
import { pipe } from '@effect/data/Function'
import * as S from '@effect/schema/Schema'

const passthrough = <I, A>(schema: S.Schema<I, A>) =>
  pipe(schema, S.extend(S.record(S.string, S.unknown)))

const schema = S.struct({ a: S.string })
console.log(S.parse(schema)({ a: 'a', b: 1 })) // { a: 'a' }
console.log(S.parse(passthrough(schema))({ a: 'a', b: 1 })) // { a: 'a', b: 1 }
```
