### ISSUE TITLE
fast-check hangs when using S.between and S.int together

### ISSUE THREAD

**Issue by zestsystem** [Effect-TS/schema#253]
### Current Behavior
fast-check hangs when using S.between and S.int together:

```ts
const Int = pipe(S.number, S.int()) // works
const NumBetweenOneAndTen = pipe(S.number, S.between(1, 10)) // works 
const IntBetweenOneAndTenAttemptOne = pipe(S.number, S.between(1, 10), S.int())   // hangs indefinitely 
const IntBetweenOneAndTenAttemptTwo = pipe(S.number, S.int(), S.between(1,10)) // hangs indefinitely

```
For now using the workaround: 

```ts
import { ArbitraryHookId, Arbitrary } from '@effect/schema/Arbitrary';

const intBetween = (min: number, max: number): S.Schema<number> => pipe(
    S.number,
    S.between(min, max),
    S.int(),
    S.annotations({
        [ArbitraryHookId]: (): Arbitrary<number> => fc => fc.integer({ min, max })
    })
);

const IntBetweenOneAndTen = intBetween(1, 10) // works
```

### Expected behavior

fast-check arbitrary should not hang when using S.between and S.int together. Or if they are meant to not be chained together, that should be explained in the documentation. 

### Additional context

I am using fast-check 3.8.1

### Your environment

Which versions of `@effect/schema` are affected by this issue? Did this work in previous versions of `@effect/schema`?

| Software      | Version(s) |
| ------------- | ---------- |
| @effect/schema |   0.16.0         |
| TypeScript    |        4.9.5    |

**Comment by gcanti** [comment]
@zestsystem should be fixed in 0.17.1
