### ISSUE TITLE
Add a `validate` method to `Schema` type to make it self-validatable

### ISSUE THREAD

**Issue by NexZhu** [Effect-TS/schema#260]
## 🚀 Feature request

Consider adding a `validate` method to `Schema` type to make it self-validatable, or adding a `Shema.toSelfValidatable` (Other possible names include `Schema.toZodLike` as suggested by tRPC team) to convert a `Schema` into `SelfValidatingSchema`.

Reason:
For something like tRPC which supports multiple validation libraries (like Zod, Yup, Superstruct) to add support for `@effect/schema` without adding `@effect/schema` as a library dependency (which is not desirable because other users may not use `@effect/schema`). A `Schema` type has to be self-validatable meaning
is has a `validate` method like:

```ts
import type { ParseOptions } from '@effect/schema/AST'

export type SelfValidatingSchema<From, To = From> = Schema<From, To> & {
  validate: (a: unknown, options?: ParseOptions) => To
}

export const toSelfValidatingSchema = <From, To = From>(
  s: Schema<From, To>,
): SelfValidatingSchema<From, To> => ({
  ...s,
  validate: Schema.validate(s),
})
```

So that schemas can be passed to tRPC library and used to validate data without the library explicitly importing `@effect/schema`.

Please see the discussion in:
https://github.com/trpc/trpc/pull/4244

**Comment by juliusmarminge** [comment]
Here's the source for how we identify the schema parser and how it works for all the libs we currently support, in case you're interested:

- https://github.com/trpc/trpc/blob/main/packages/server/src/core/internals/getParseFn.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/core/parser.ts

**Comment by gcanti** [comment]
Thanks @juliusmarminge, based on the type of `Parser`, looks like we happen to already produce a custom validator:

```ts
import * as S from '@effect/schema/Schema'

export type ParserCustomValidatorEsque<TInput> = (
  input: unknown
) => TInput | Promise<TInput>

const parse1: ParserCustomValidatorEsque<number> = S.parse(S.number)
const parse2: ParserCustomValidatorEsque<number> = S.parsePromise(S.number)
```

**Comment by juliusmarminge** [comment]
Yea you fulfill the types, it's the runtime validator that doesn't work right now as it's on this library itself and not the schema

For example, with Zod

```ts
import {z} from "zod";
const user = z.object({
  id: z.string()
}).parse(someObj);
```

Whereas effect would be

```ts
import * as S from "@effect/schema";
const user = S.parse(
  S.struct()
);
```

Which means to get the parse function we'd need a dependency on effect cause it's not passed on the schema itself.

Alternatively, we could have a wrapper that would live in userland:

```ts
const myProc = t.input(
  S.toSelfParseable(S.struct())
  ...
```

What do you think?

**Comment by gcanti** [comment]
AFAIK `t.input` and `t.output` accept a custom validator

```ts
import { initTRPC } from '@trpc/server'
import * as S from '@effect/schema/Schema'

const t = initTRPC.create()

const appRouter = t.router({
  userById: t.procedure
    .input(S.parse(S.string))
    .output(S.parse(S.number))
    .query(async (opts) => {
      const { input } = opts
      //        ^ string
      return input.length
    })
})
```

**Comment by NexZhu** [comment]
@gcanti Adding a wrapper won't be useful then, as it would be similar to just using `S.parse` and passing the custom validator function. Will you consider adding a `validate` method to `Schema` type so tRPC can natively support `@effect/schema` schemas? If not, your approach above also work well enough for me, just a bit more verbose.

**Comment by juliusmarminge** [comment]
> AFAIK `t.procedure.input` and `t.procedure.output` accept a custom validator
> 
> ```ts
> import { initTRPC } from '@trpc/server'
> import * as S from '@effect/schema/Schema'
> 
> const t = initTRPC.create()
> 
> const appRouter = t.router({
>   userById: t.procedure
>     .input(S.parse(S.string)) // ParserCustomValidatorEsque
>     .output(S.parse(S.number)) // ParserCustomValidatorEsque
>     .query(async (opts) => {
>       const { input } = opts
>       //        ^ string
>       return input.length
>     })
> })
> ```

Oh duh... My bad - I should've tested that, I just assumed since OP used a 3rd party lib it didn't work for some reason - but it totally does!
