### ISSUE TITLE
Filter for number with n digits

### ISSUE THREAD

**Issue by mjljm** [Effect-TS/schema#288]
## 🚀 Feature request
A filter to add to the Number filters list that checks if a number has at most n decimal placeholders.

### Suggested Solution

```ts
export const hasNDecimals = (n: number) =>
	S.filter<number, number>(
		(m) => {
			const o = m * Math.pow(10, n);
			return Math.trunc(o) === o;
		},
		{
			message: () => `a number with ${n} decimal places`
		}
	);
````

### Who does this impact? Who is this for?

Can come in handy for instance when you work with money and want to check numbers have at most 2 significant digits.

### Describe alternatives you've considered
None

### Your environment

| Software      | Version(s) |
| ------------- | ---------- |
| @effect/schema |      0.19.3      |
| TypeScript    |     5.1.0-tsplus.20230423       |

**Comment by gcanti** [comment]
About the implementation, if I'm not wrong should be equivalent to `multipleOf`, e.g.

2 decimals => `multipleOf(0.01)`

**Comment by mjljm** [comment]
Yes sorry, I absolutely need to go through the code as there is a lot more to Schema than what stands in the docs.

I am closing this issue.

Have a great day.

**Comment by gcanti** [comment]
Indeed, `multipleOf` is not even mentioned in the README. I will correct it asap
