### ISSUE TITLE
provide an Email schema ?

### ISSUE THREAD

**Issue by err0r500** [Effect-TS/schema#294]
### Current Behavior

No Email schema provided by this package. Same result is achievable with a custom Pattern, though.

### Desired Behavior

Email schema is a quite frequent need for business apps. Would be nice to provide it out-of-the-box (and use the corresponding arbitrary in fast-check)

### Suggested Solution

Should be easy to add the schema, not sure if the proliferation of ad-hoc schemas is desirable.

### Alternative Solution
Use a Pattern schema

### Who does this impact? Who is this for?

It would be for everyone

**Comment by gcanti** [comment]
Considering all the issues that `email()` has caused in Zod, I'm against adding such a schema

**Comment by err0r500** [comment]
I was not aware of that. Ok, I close the issue ;)
