### ISSUE TITLE
Combination of S.nullable and prop.opt

### ISSUE THREAD

**Issue by schickling** [Effect-TS/schema#37]
**Is your feature request related to a problem? Please describe.**

When when modelling an object using `S.props` it's currently possible to make a field "nullable or optional" using

1. `myProp: S.prop(S.nullable(S.string))`
2. `myProp: S.prop(S.string).opt()`

(1) results in accepting `null` or `"some-str"` as value and being parsed into `myProp: O.Option<string>`.
(2) results in accepting `undefined`, `"some-str"` or omitting the field and being parsed into `byProp: string | undefined`.

**Describe the solution you'd like**

I'd like something "in between". Basically something that allows me to omit a field like in (2) but being parsed into an option like in (1)

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by patroza** [comment]
This is already ‘S.prop(nullable(string)).opt()’

**Comment by patroza** [comment]
Actually, this works as expected:

```ts
const a = S.props({
  a: S.prop(S.string).opt(),
  b: S.prop(S.nullable(S.string)),
  c: S.prop(S.nullable(S.string)).opt(),
  d: S.prop(S.nullable(S.string)).def(() => O.none),
})

type I = S.ParserInputOf<typeof a>
type E = S.EncodedOf<typeof a>
type A = S.ParsedShapeOf<typeof a>

const parser = S.Parser.for(a)["|>"](S.unsafe)
console.log(
  parser({
    b: "abc",
  })
)
```

with the exception that the E type will loose `| undefined` for `d`. But imo that is correct.

**Comment by schickling** [comment]
Thanks for your elaborate example. In my case I actually **do want** the "lossy parsing -> encoding" scenario since in my case I rather want to keep the accepted input data more flexible (i.e. allow for both `null` and explicit / implicit `undefined values) while keeping my implementation when working with the data simple by just working with `Option<string>` where I don't care whether the original data was `null` or `undefined`.

**Comment by patroza** [comment]
> Thanks for your elaborate example. In my case I actually **do want** the "lossy parsing -> encoding" scenario since in my case I rather want to keep the accepted input data more flexible (i.e. allow for both `null` and explicit / implicit `undefined values) while keeping my implementation when working with the data simple by just working with `Option`where I don't care whether the original data was`null`or`undefined`.

alright, what you want is this:
```ts
export type ParserInputFromProperties<Props extends PropertyRecord> = Compute<
  UnionToIntersection<
    {
      [k in keyof Props]: Props[k] extends AnyProperty
        ? Props[k]["_optional"] extends "optional"
          ? {
              readonly [h in Props[k]["_as"] extends O.Some<any>
                ? Props[k]["_as"]["value"]
                : k]?: S.EncodedOf<Props[k]["_schema"]>
            }
          : Props[k]["_def"] extends O.Option<["parser" | "both", any]>
          ? {
              readonly [h in Props[k]["_as"] extends O.Some<any>
                ? Props[k]["_as"]["value"]
                : k]?: S.EncodedOf<Props[k]["_schema"]>
            }
          : {
              readonly [h in Props[k]["_as"] extends O.Some<any>
                ? Props[k]["_as"]["value"]
                : k]: S.EncodedOf<Props[k]["_schema"]>
            }
        : never
    }[keyof Props]
  >,
  "flat"
>
`

`type PI = S.ParserInputFromProperties<typeof a["Api"]["props"]>`
<img width="477" alt="Screenshot 2021-05-30 at 14 28 29" src="https://user-images.githubusercontent.com/42661/120104149-6243f800-c153-11eb-978f-000aa3161d1d.png">
