### ISSUE TITLE
Make interpreters extensible

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/schema#49]
## 🚀 Feature request

I suggest that we refactor the current interpreters to allow the user to customize how the schema is interpreted. Similar to how the [experimental schema interpreters in io-ts](https://github.com/gcanti/io-ts/blob/master/Schema.md) could be extended. This would make it possible to create new interpreters from existing interpreters or allow the user to make minor changes to how a schema is interpreted. 

The change to the interpreters could be something as simple as accepting a map(which is passed as an argument) instead of using a hard code case statement. 

```js
export const defaultMapping: ASTMap<Pretty<any>> = {
  "TemplateLiteral": (ast) => make(I.makeSchema(ast), (s) => String(s)),
  "UndefinedKeyword": (ast) => make(I.makeSchema(ast), () => "undefined"),
  "VoidKeyword": (ast) => make(I.makeSchema(ast), () => "void(0)"),
  "UnknownKeyword": (ast) => make(I.makeSchema(ast), (a) => JSON.stringify(a, null, 2)),
  // ...
}

const prettyFor = (map: ASTMap<Pretty<any>> = defaultMapping) =>
  <A>(schema: Schema<A>): Pretty<A> => {
    const go = (ast: AST.AST): Pretty<any> => map[ast._tag](ast, go)

    return go(schema.ast)
  }

export const pretty = (map: ASTMap<Pretty<any>> = defaultMapping) => 
    <A>(schema: Schema<A>) => (a: A): string => prettyFor(map)(schema).pretty(a)

// Test case

it("boolean", () => {
  const schema = S.boolean
  const pretty = P.pretty()(schema)
  expect(pretty(true)).toEqual("true")
})

it("boolean - custom", () => {
  const schema = S.boolean
  const pretty = P.pretty({
    ...P.defaultMapping,
    "BooleanKeyword": (ast) => P.make(I.makeSchema(ast), (s) => String(s).toUpperCase())
  })(schema)

  expect(pretty(true)).toEqual("TRUE")
})
```

**Comment by mattiamanzati** [comment]
Not sure, but back in the experimentation days it was exactly how you described (see https://github.com/fp-ts/schema/commit/f61070aeced3424c5f067bbc41a55709a80af637) but was killed being too cumbersome, and was easier to just alias standard types (e.g. S.boolean) or completely redefine the interperet (reusing where available the default one), as it just maps over a set of known cases.
