### ISSUE TITLE
Add support for `BigDecimal`

### ISSUE THREAD

**Issue by fubhy** [Effect-TS/schema#576]
### What is the problem this feature would solve?

We've "recently" added a `BigDecimal` module to `effect`. Let's add support for that to `/schema`

### What is the feature you are proposing to solve the problem?

... see above :-)

**Comment by jessekelly881** [comment]
@fubhy Mind if I grab this?

**Comment by fubhy** [comment]
> @fubhy Mind if I grab this? Or have you already started it?

Be my guest!
