### ISSUE TITLE
import * as S from "@effect/schema/Schema" not working in React Native Expo

### ISSUE THREAD

**Issue by steida** [Effect-TS/schema#598]
### What version of `@effect/schema` is running?

0.49.4

### What steps can reproduce the bug?

1. `npx create-expo-app my-app`
2. Add "@effect/schema": "^0.49.4",
3. Try to use it.

### What is the expected behavior?

Importing should work.

### What do you see instead?

![Screenshot 2023-11-23 at 18 51 37](https://github.com/Effect-TS/schema/assets/66249/f762f495-1c0c-4b6b-a649-6b2a4e245e97)

**Comment by steida** [comment]
`import * as S from "@effect/schema";`

![Screenshot 2023-11-23 at 19 03 17](https://github.com/Effect-TS/schema/assets/66249/0ab03332-4097-4cc1-aa42-d25b5c533c04)

**Comment by steida** [comment]
So, when I enable Metro  `unstable_enablePackageExports`, it works.

Except Schema needs a `fast-text-encoding` polyfill that should be noted in docs.

But without `unstable_enablePackageExports`, it's still not working.

**Comment by fubhy** [comment]
Afaik, without `enablePackageExports` this only works by publishing `dist` with proxy packages (sub-directories in the root of `dist` with their own `package.json` pointing at the right files with `main` and `module` respectively).

I'm not sure if we want to add that across all our packages or not. But afaik there's no other way.

./cc @jxom (please verify this statement)

**Comment by mikearnaldi** [comment]
We could add them to the build scripts and have them on all the packages

**Comment by fubhy** [comment]
Yeah. Generating those should be fairly simple. It would likely also mean that we can go back to having `dist/cjs` instead of dropping the cjs files into the root. The proxy packages would then point at the right `dist/cjs` files.

./cc @tim-smart

**Comment by fubhy** [comment]
This could work: https://github.com/Effect-TS/build-utils/pull/44

**Comment by steida** [comment]
@fubhy With RN 0.73, exports will be enabled by default.

**Comment by fubhy** [comment]
> @fubhy With RN 0.73, exports will be enabled by default.

That's nice. But we might still want to support older versions for ppl who are stuck there. At least for some time.

**Comment by tim-smart** [comment]
Will marked this as closed, as it has been fixed now :)
